# Generated by Django 3.2.6 on 2021-08-05 14:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('thumbnails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
