# Generated by Django 3.2.6 on 2021-08-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='thumbnails',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
