# Generated by Django 3.2.6 on 2021-08-05 16:44

from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0002_alter_youtube_thumbnails"),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
